apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  PG_HOST: {{ .Values.postgres.host }}
  PORT: {{ .Values.postgres.port | quote }}
  ACCESS_TOKEN: {{ .Values.accessToken }} 